version: '2'
services:
    ui:
        build:
            context: .
            dockerfile: Dockerfile.ui
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
            args:
                - DAYTONA_USER=admin
                - DAYTONA_PASSWORD=admin

        environment:
            MYSQL_ROOT_PASSWORD: daytona_admin
            MYSQL_DATABASE: daytona
            MYSQL_USER: daytona
            MYSQL_PASSWORD: anotyadPassword
        ports:
            - "3306:3306"
    agent:
           build: 
               context: .
               dockerfile: Dockerfile.agent
